# Generated by Django 4.2.4 on 2023-08-26 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_userprofile_delete_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
