# Generated by Django 4.2.4 on 2023-09-26 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_usuarionornir'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuarionornir',
            table='usuario_nornir',
        ),
    ]
