---
inventory:
    plugin: SimpleInventory
    options:
        host_file: "/home/kevin/junos-networkAutomation/firstGalance/inventory/hosts.yaml"
        group_file: "/home/kevin/junos-networkAutomation/firstGalance/inventory/groups.yaml"
        defaults_file: "/home/kevin/junos-networkAutomation/firstGalance/inventory/defaults.yaml"
runner:
    plugin: threaded
    options:
        num_workers: 5